{% set name = "extract_model" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/extract_model/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1dee0ca4ae531f9cddb95ca862e76e2ffa534fc9e7c3927f06adccf577872142

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - cf_xarray >=0.6
    - cmocean
    - dask
    - jupyter
    - jupyterlab
    - matplotlib-base
    - netcdf4
    - numpy
    - python >=3.6
    - pytest
    - requests
    - xarray
    - xcmocean
    - xesmf

test:
  imports:
    - extract_model
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/extract_model
  license: MIT
  license_file: LICENSE.txt
  summary: Facilitates read-in and extraction for ocean model output.
  doc_url: https://extract-model.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/extract_model

extra:
  recipe-maintainers:
    - kthyng
