{% set name = "extract_model" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/extract_model/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91afb9ec71e197e9d0016eaeccd1bf0b5fe027b35027d3e3ac25c30a3b78764e

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - cartopy
    - cf_xarray
    - cmocean
    - dask
    - jupyter
    - jupyterlab
    - matplotlib-base
    - netcdf4
    - numba
    - numpy
    - python >=3.6
    - pytest
    - requests
    - xarray
    - xcmocean
    - xesmf
    # - pip:  # install from github to get recent PRs I contributed
    #   - git@github.com:xarray-contrib/cf-xarray.git

test:
  imports:
    - extract_model
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/extract_model
  license: MIT
  license_file: LICENSE.txt
  summary: Facilitates read-in and extraction for ocean model output.
  doc_url: https://extract-model.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/extract_model

extra:
  recipe-maintainers:
    - kthyng
