{% set name = "extract_model" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/axiom-data-science/extract_model/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6505dda14410b35c1e12725b4c0b618f55d5e727890864cbe9982d91f549e15f

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - cf_xarray
    - netcdf4
    - numpy
    - python >={{ python_min }}
    - requests
    - scikit-learn  # for xoak tree
    - xarray
    # - pip:  # install from github to get recent PRs I contributed
    #   - git@github.com:xarray-contrib/cf-xarray.git

test:
  imports:
    - extract_model
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/axiom-data-science/extract_model
  license: MIT
  license_file: LICENSE.txt
  summary: Facilitates read-in and extraction for ocean model output.
  doc_url: https://extract-model.readthedocs.io/
  dev_url: https://github.com/axiom-data-science/extract_model

extra:
  recipe-maintainers:
    - kthyng
